Added 5 modules to Design Patterns Java Series
AutomateThePlanet/AutomateThePlanet-Learning-Series pull request #12
Opened 2021-01-13 10:42 UTC by teo-nikolov

2021-01-13 10:58 UTC, teo-nikolov commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/strategyadvanced/core/BasePage.java
> +import pageobjectadvanced.core.ReflectionNewInstanceFactory;
should import **strategyadvanced.core.ReflectionNewInstanceFactory** instead, will fix in next commit

2021-01-13 11:09 UTC, angelovstanton requested changes

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/decorator/services/CouponCodeCalculationService.java
> +    public double calculate(double price, String couponCode) {
leave empty line

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/decorator/services/VatTaxCalculationService.java
> +    public double calculate(double price, Country country) {
leave empty line

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/pageobjectadvanced/core/Driver.java
> +                //setBrowser(new ChromeDriver());
uncomment this everywhere and make it work :)

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/strategy/core/BasePage.java
> +    @SuppressWarnings("unchecked")
even if the methods are with different access modifiers  I believe it is more readable elements and assertions to be placed together one after another. I added similar note I think to the advanced page object model article. This follows Oracle Java convention and it is OK.

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/strategy/core/Driver.java
> +            Thread.sleep(1000);
no need

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/strategy/core/ReflectionNewInstanceFactory.java
> +            var elementsClass = (Class) ((ParameterizedType) getClass
remove spaces, I commented it above

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/strategy/pages/itempage/ItemAssertions.java
> +public class ItemAssertions extends BaseAssertions<ItemElements> {}
do you need empty assertions class?

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/strategyadvanced/StorePurchaseAdvancedStrategyTests.java
> +        new PurchaseContext(new VatTaxOrderPurchaseStrategy(), new CouponCodeOrderPurchaseStrategy())
purchaseItem

2021-01-13 11:09 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/strategyadvanced/core/Driver.java
> +            Thread.sleep(1000);
no need

2021-01-15 15:16 UTC, angelovstanton approved these changes

2021-01-15 15:16 UTC, angelovstanton commented on DesignPatternsInAutomatedTestingJava-Series/src/test/java/decorator/core/Driver.java
> + * Author: Anton Angelov
you can set your name here :)

2021-01-15 15:17 UTC, merged